modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="morecommands"
version="1.0.0"
displayName="MoreCommands"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Block_Legend001"
description='''
A simple mod, that add a lots of commands
'''

[[dependencies.morecommands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




